### ISSUE TITLE
把网断了,数据还在不断的增加,牛B

### ISSUE THREAD

**Issue by rolitter** [PGYER/frontend-tracker#2]
![image](https://user-images.githubusercontent.com/27326998/34510794-0a254aba-f092-11e7-8b84-680c311e6716.png)

**Comment by cubicwork** [comment]
这里显示的近似结果是按照截止当日0点前的数据量作为基数，前一天的数据量计算增长率，推测出的实时数据，虽然数据不一定准确，但是可以大致的反映实时的增长。我们没必要为表面上的工作耗费更多的机器资源

**Comment by callmesoul** [comment]
还有这等操作..
